extends Node3D

# Environment
const ENVIRONMENT_GRAVITY = 9.8
const ENVIRONMENT_AIR_INERTIA = 7.0
const ENVIRONMENT_GROUND_INERTIA = 7.0

# Player
const PLAYER_SPEED_WALK = 10.0
const PLAYER_CLIMBING_SPEED = 10.0
const PLAYER_JUMP_OVER_LEDGE_VELOCITY = 25.0
const PLAYER_TIME_BETWEEN_DASHES_LENGTH = 0.3  # In seconds
const PLAYER_ROTATION_SPEED = 25
# Player dashing
const PLAYER_DASH_SPEED = 50.0
const PLAYER_DASH_LENGTH = 0.2  # In seconds
const PLAYER_DASH_UPWARDS_BOOST = 25
const PLAYER_DASHES_ALLOWED = 1
const PLAYER_NUMBER_OF_DASH_GHOSTS = 5
const PLAYER_GHOST_FADE_LENGTH = 0.5
const PLAYER_GHOST_STARTING_ALPHA = 0.5
# Player Jumping
const PLAYER_JUMP_BUFFER_TIME = 0.1
const PLAYER_JUMP_COYOTE_TIME = 0.1
const PLAYER_JUMP_HEIGHT = 7.0
const PLAYER_JUMP_TIME_TO_PEAK = 0.3
const PLAYER_JUMP_TIME_TO_DESCENT = 0.2
const PLAYER_WALL_JUMP_Y_MULTIPLIER = 0.7
const PLAYER_WALL_JUMP_X_MULTIPLIER = 1.7

# UI
const UI_SENSITIVITY = 0.3
const UI_BASE_FOV = 75.0
const UI_FOV_CHANGE = 1.5

# Persistant variables
var wonGame = false
